# Generated by Django 5.1.4 on 2025-01-10 23:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='человекопонятный URL', max_length=255, verbose_name='Слан')),
                ('short_text', models.TextField(verbose_name='Краткое содержание')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент статьи')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='articles/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Отображать на главной странице')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Статьи и новости',
            },
        ),
    ]
