# Generated by Django 5.1.4 on 2025-01-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бренда')),
                ('slug', models.SlugField(help_text='человекопонятный URL', max_length=255, unique=True, verbose_name='Слан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название Категории')),
                ('slug', models.SlugField(help_text='человекопонятный URL', max_length=255, unique=True, verbose_name='Слан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='products/parts/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название запасной части')),
                ('slug', models.SlugField(help_text='человекопонятный URL', max_length=255, unique=True, verbose_name='Слан')),
                ('small_text', models.TextField(verbose_name='Краткое описание')),
                ('state', models.CharField(choices=[('new', 'Новый'), ('used', 'Бывший в эксплуатации')], default='new', help_text='Выберите состояние', max_length=255, verbose_name='Состояние')),
                ('sku', models.CharField(help_text='Укажите артикул запасной части', max_length=255, verbose_name='Артикул')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте', verbose_name='Активность')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_featered', models.BooleanField(default=False, help_text='Отображать на главной странице', verbose_name='Рекомендуемый')),
                ('brand', models.ForeignKey(help_text='Выберите бренд для совместимости', on_delete=django.db.models.deletion.CASCADE, to='parts.brand', verbose_name='Совместимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запасная часть',
                'verbose_name_plural': 'Запасные части',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Мета-ключевые слова')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Настройка СЕО')),
            ],
        ),
    ]
