# Generated by Django 5.1.4 on 2025-01-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бренда')),
                ('slug', models.SlugField(help_text='человекопонятный URL', max_length=255, unique=True, verbose_name='Слан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='products/towers/', verbose_name='Изображение')),
                ('name', models.CharField(help_text='Башенный кран YONGMAO 3100', max_length=255, verbose_name='Название крана')),
                ('slug', models.SlugField(help_text='человекопонятный URL', max_length=255, unique=True, verbose_name='Слан')),
                ('small_text', models.TextField(verbose_name='Краткое описание')),
                ('state', models.CharField(choices=[('new', 'Новый'), ('used', 'Бывший в эксплуатации')], default='new', help_text='Выберите состояние', max_length=255, verbose_name='Состояние')),
                ('max_load_capacity', models.DecimalField(decimal_places=2, help_text='Укажите максимальную грузоподъемность в тоннах', max_digits=10, verbose_name='Грузоподъемность макс. (тонн)')),
                ('max_reach', models.DecimalField(decimal_places=2, help_text='Укажите максимальный вылет стрелы в метрах', max_digits=10, verbose_name='Макс. вылет стрелы (м)')),
                ('load_at_max_reach', models.DecimalField(decimal_places=2, help_text='Укажите грузоподъемность на максимальном вылете стрелы в тоннах', max_digits=10, verbose_name='Грузоподъемность на макс. вылете (тонн)')),
                ('hook_height', models.DecimalField(decimal_places=2, help_text='Укажите максимальную высоту подъема крюка в метрах', max_digits=10, verbose_name='Высота подъема крюка (м)')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте', verbose_name='Активность')),
                ('is_featered', models.BooleanField(default=False, help_text='Отображать на главной странице', verbose_name='Рекомендуемый')),
                ('brand', models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='towers.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Башенный кран',
                'verbose_name_plural': 'Башенные краны',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Мета-ключевые слова')),
                ('crane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='towers.crane', verbose_name='Настройка СЕО')),
            ],
        ),
    ]
