# Generated by Django 5.1.4 on 2025-01-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте', verbose_name='Активность')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображать на главной странице', verbose_name='Рекомендуемый')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
